GET http://localhost:8080

###
GET http://localhost:8080/todos


###
GET http://localhost:8080/todos/8

###

POST http://localhost:8080/todos
Content-Type: application/json

{
    "title":"Master 3DS Max",
    "completed":true
}

###

DELETE  http://localhost:8080/todos/10
Content-Type: application/json

###

POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email":"titi@gmail.com",
    "password":"123456"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email":"rhoda@gmail.com",
    "password":"123456"
}

###

POST http://localhost:8080/auth/refresh
Content-Type: application/json

###

GET http://localhost:8080/protected-test

###

GET http://localhost:8080/admin/users


###

GET http://localhost:8080/admin/todos

###

POST http://localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJob2RhQGdtYWlsLmNvbSIsImV4cCI6MTc3NzczMTMzMCwicm9sZSI6InVzZXIiLCJ1c2VyX2lkIjoiM2VjYjY0Y2ItMDQzOC00MjkwLWE5MDktMThkMTI1ZGJmYWQ5In0.iZxTFsWRaS8qM1l8R9HcRgtBwwSE7NYyhUx0aeS0Kp0

{
  "refresh_token": "1b314b4f928fd79327dc914b08a9f8dbc08099cf4f86363be3de951dd5d5719c0fc3e8cad3b1a3bb3e858b9e12a2b75cad017aa2fddf12f6848ff35c4f6eb21b",
  "all_devices": true
}
